### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by ebastidas** [SchweizerischeBundesbahnen/esta-webjs#19]
I installed it with the yeoman esta-webjs generator and ran it. The application starts normally in the port 3001 (http://localhost:3001/). When I click in the login button of the starter app it redirects me to: http://localhost:9999/, which is not found because of the port 9999 is not the one being used.

I can see that this port "9999" is hardcoded in two files (src/app/app.js, docker/start.sh). I tried to change this 9999 port value to the port where the app starts ("3001") but it doesn't fix the link to the login problem. How to solve this?

**Comment by ReToCode** [comment]
This port is the login server not the frontend (3001). If you want to use the login functionality you need to have an oauth2-compatible auth-server. E.g. https://spring.io/guides/tutorials/spring-boot-oauth2/. Run this server on port 9999.
