### ISSUE TITLE
"yo esta-webjs" failing with 'esta-webjs-style' is not in the npm registry

### ISSUE THREAD

**Issue by morarupasukaru** [SchweizerischeBundesbahnen/esta-webjs#2]
I try to create an ESTA WebJS project outside SBB Network for a private training project (i work as "externe", => ue58394).

After having installed "esta-webjs" generator, i call the generator to create a project.

Console output of "yo esta-webjs":

pascal@pascal:~/Documents/dev/dico/esta-webjs/dico-webjs$ yo esta-webjs

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |   ESTA WebJS generator   |
   `---------´   |           1.0.1          |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Please answer the following questions
_____________________________________
? What is the project name dico-webjs
? What is the project description Dictionnary
? What is the project version 1.0.0
? What is the maven groupId edu.lang
? What is the maven artifactId edu.lang.dico-webjs
_____________________________________
Going to create your project
ProjectName: dico-webjs
ProjectVersion: 1.0.0
Maven GroupId: edu.lang
Maven ArtifactId: edu.lang.dico-webjs
Now copying all files for starterkit
Now copying all templated files for starterkit

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

   create package.json
   create .jshintrc
   create assembly.xml
   create docker/Dockerfile
   create docker/start.sh
   create gulpfile.babel.js
   create karma.conf.js
   create pom.xml
   create spec.bundle.js
   create src/app/app.component.js
   create src/app/app.css
   create src/app/app.html
   create src/app/app.js
   create src/app/components/common/about/about.component.js
   create src/app/components/common/about/about.controller.js
   create src/app/components/common/about/about.css
   create src/app/components/common/about/about.html
   create src/app/components/common/about/about.js
   create src/app/components/common/about/about.spec.js
   create src/app/components/common/common.js
   create src/app/components/common/home/home.component.js
   create src/app/components/common/home/home.controller.js
   create src/app/components/common/home/home.html
   create src/app/components/common/home/home.js
   create src/app/components/common/home/home.spec.js
   create src/app/components/common/messages/messages.component.js
   create src/app/components/common/messages/messages.controller.js
   create src/app/components/common/messages/messages.html
   create src/app/components/common/messages/messages.js
   create src/app/components/common/messages/messages.service.js
   create src/app/components/common/messages/messages.spec.js
   create src/app/components/common/navbar/navbar.component.js
   create src/app/components/common/navbar/navbar.controller.js
   create src/app/components/common/navbar/navbar.html
   create src/app/components/common/navbar/navbar.js
   create src/app/components/common/navbar/navbar.spec.js
   create src/app/components/common/posts/posts.js
   create src/app/components/common/posts/posts.service.js
   create src/app/components/common/posts/posts.spec.js
   create src/app/components/common/theme/theme.component.js
   create src/app/components/common/theme/theme.controller.js
   create src/app/components/common/theme/theme.html
   create src/app/components/common/theme/theme.js
   create src/app/components/common/theme/theme.spec.js
   create src/app/components/components.js
   create src/app/components/security/interceptor/interceptor.js
   create src/app/components/security/interceptor/interceptor.service.js
   create src/app/components/security/interceptor/interceptor.spec.js
   create src/app/components/security/login/login.js
   create src/app/components/security/oauth/oauth.js
   create src/app/components/security/oauth/oauth.service.js
   create src/app/components/security/oauth/oauth.spec.js
   create src/app/components/security/security.js
   create src/app/languages/lang-de.json
   create src/app/languages/lang-en.json
   create src/index.html
   create src/README.md
   create webpack.config.js
npm ERR! Linux 3.19.0-49-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.3.0
npm ERR! npm  v3.7.5
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/esta-webjs-style
npm ERR! 404 
npm ERR! 404  'esta-webjs-style' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'dico-webjs'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pascal/Documents/dev/dico/esta-webjs/dico-webjs/npm-debug.log

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |   Everything is ready -  |
   `---------´   |   open your console and  |
    ( _´U`_ )    |       type "gulp"!       |
    /___A___\    '--------------------------'
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

is "esta-webjs-style" another npm package to be hosted in github?

**Comment by ReToCode** [comment]
We are aware of this problem. We are currently checking if it is possible to host this package on github and as package on the npmjs registry. Problem is, that there are custom fonts in that package.

As a workaround:
- Remove the package from package.json
- Remove the import statement in app.js
- Delete node_modules folder
- Run 'npm install'

Your application should no work. Only difference is that you don't have the SBB layout and styles.

**Comment by morarupasukaru** [comment]
Thank you for the explanation. Indeed, the application is building and running correctly.
